// All 12 SMVP HQ Agents — single source of truth
export const AGENTS = [
  // Tier 1: Front Office (Client-Facing)
  {
    id: 'rex',
    name: 'Rex',
    role: 'Lead Hunter & Market Research',
    tier: 'front-office',
    emoji: '\u{1F50D}',
    color: '#2563EB',
    status: 'idle',
    autonomy: 30,
    description: 'Finds and qualifies leads, researches markets, builds prospect lists.',
    taskLimit: 3,
  },
  {
    id: 'ace',
    name: 'Ace',
    role: 'Sales Closer & Client Relations',
    tier: 'front-office',
    emoji: '\u{1F91D}',
    color: '#7C3AED',
    status: 'idle',
    autonomy: 20,
    description: 'Drafts outreach, manages client communication, closes deals.',
    taskLimit: 3,
  },
  {
    id: 'nova',
    name: 'Nova',
    role: 'Content Writer & Copywriter',
    tier: 'front-office',
    emoji: '\u{270D}\u{FE0F}',
    color: '#EC4899',
    status: 'idle',
    autonomy: 40,
    description: 'Writes blog posts, ad copy, email sequences, landing pages.',
    taskLimit: 3,
  },
  {
    id: 'dash',
    name: 'Dash',
    role: 'Analytics & Reporting',
    tier: 'front-office',
    emoji: '\u{1F4C8}',
    color: '#06B6D4',
    status: 'idle',
    autonomy: 60,
    description: 'Tracks KPIs, generates reports, monitors performance across all agents.',
    taskLimit: 5,
  },

  // Tier 2: Back Office (Production)
  {
    id: 'pixel',
    name: 'Pixel',
    role: 'Web Designer & Developer',
    tier: 'back-office',
    emoji: '\u{1F3A8}',
    color: '#F97316',
    status: 'idle',
    autonomy: 25,
    description: 'Designs and builds websites, landing pages, web applications.',
    taskLimit: 2,
  },
  {
    id: 'prism',
    name: 'Prism',
    role: 'Creative Producer',
    tier: 'back-office',
    emoji: '\u{1F3AC}',
    color: '#A855F7',
    status: 'idle',
    autonomy: 30,
    description: 'Creates videos, graphics, Printify designs, visual assets.',
    taskLimit: 3,
  },
  {
    id: 'echo',
    name: 'Echo',
    role: 'Social Media Manager',
    tier: 'back-office',
    emoji: '\u{1F4F1}',
    color: '#14B8A6',
    status: 'idle',
    autonomy: 35,
    description: 'Manages 8 social platforms, schedules posts, engages audience.',
    taskLimit: 4,
  },
  {
    id: 'sentry',
    name: 'Sentry',
    role: 'QA & Brand Compliance',
    tier: 'back-office',
    emoji: '\u{1F6E1}\u{FE0F}',
    color: '#EAB308',
    status: 'idle',
    autonomy: 50,
    description: 'Reviews all outputs for quality, brand compliance, WCAG, legal.',
    taskLimit: 5,
  },
  {
    id: 'shelf',
    name: 'Shelf',
    role: 'Store Manager',
    tier: 'back-office',
    emoji: '\u{1F3EA}',
    color: '#84CC16',
    status: 'idle',
    autonomy: 30,
    description: 'Manages Etsy, TikTok Shop, Canva Store listings and orders.',
    taskLimit: 3,
  },

  // Tier 3: Infrastructure
  {
    id: 'cortex',
    name: 'Cortex',
    role: 'Orchestrator & COO',
    tier: 'infrastructure',
    emoji: '\u{1F9E0}',
    color: '#6366F1',
    status: 'idle',
    autonomy: 40,
    description: 'Routes tasks, resolves deadlocks, manages agent coordination.',
    taskLimit: 10,
  },
  {
    id: 'flux',
    name: 'Flux',
    role: 'DevOps & Deployment',
    tier: 'infrastructure',
    emoji: '\u{2699}\u{FE0F}',
    color: '#64748B',
    status: 'idle',
    autonomy: 20,
    description: 'Deploys code, monitors uptime, manages infrastructure.',
    taskLimit: 3,
  },
  {
    id: 'ledger',
    name: 'Ledger',
    role: 'Finance & CFO',
    tier: 'infrastructure',
    emoji: '\u{1F4B0}',
    color: '#22C55E',
    status: 'idle',
    autonomy: 10,
    description: 'Tracks revenue, expenses, P&L, tax calculations. Reports only.',
    taskLimit: 3,
  },
]

export const TIERS = {
  'front-office': { label: 'Front Office', description: 'Client-Facing' },
  'back-office': { label: 'Back Office', description: 'Production' },
  'infrastructure': { label: 'Infrastructure', description: 'Operations' },
}

export function getAgent(id) {
  return AGENTS.find(a => a.id === id)
}

export function getAgentsByTier(tier) {
  return AGENTS.filter(a => a.tier === tier)
}
